services:

  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  client-gateway:
    image: client-gateway-prod
    build: 
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - PRODUCTS_MICROSERVICE_HOST=${PRODUCTS_MICROSERVICE_HOST}
      - PRODUCTS_MICROSERVICE_PORT=${PRODUCTS_MICROSERVICE_PORT}
      - ORDERS_MICROSERVICE_HOST=${ORDERS_MICROSERVICE_HOST}
      - ORDERS_MICROSERVICE_PORT=${ORDERS_MICROSERVICE_PORT}
      - PAYMENTS_MICROSERVICE_HOST=${PAYMENTS_MICROSERVICE_HOST}
      - PAYMENTS_MICROSERVICE_PORT=${PAYMENTS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    
  products-ms:
    image: products-ms-prod
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    ports:
      - ${PRODUCTS_MICROSERVICE_PORT}:${PRODUCTS_MICROSERVICE_PORT}
    environment:
      - PORT=${PRODUCTS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${DATABASE_URL}

  orders-ms:
    image: orders-ms-prod
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL} # Esto es un ejemplo de como pasar variables de entorno al Dockerfile o argumentos
    ports:
      - ${ORDERS_MICROSERVICE_PORT}:${ORDERS_MICROSERVICE_PORT}
    environment:
      - PORT=${ORDERS_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - PRODUCTS_MICROSERVICE_HOST=${PRODUCTS_MICROSERVICE_HOST}
      - PRODUCTS_MICROSERVICE_PORT=${PRODUCTS_MICROSERVICE_PORT}
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    depends_on:
      - orders-db

  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  payments-ms:
    image: payments-ms-prod
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:${PAYMENTS_MICROSERVICE_PORT}
    environment:
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - ORDERS_MICROSERVICE_HOST=localhost
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - SECRET_ENDPOINT=${SECRET_ENDPOINT}

  auth-ms:
    image: auth-ms-prod
    build: 
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    ports:
      - ${AUTH_MICROSERVICE_PORT}:${AUTH_MICROSERVICE_PORT}
    environment:
      - PORT=${AUTH_MICROSERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${DATABASE_URL_MONGO}
      - SECRET=${SECRET_JWT}
  
  # Add more microservices here
  # TODO: optimze the Dockerfile.prod for each microservice